#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=select_reformulate
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=15
#SBATCH --time=01:00:00
#SBATCH --output=outputs/slurm_output_sar_%A.out

# This script executes a SAR pipeline.

module purge
module load 2024
module load Anaconda3/2024.06-1

source jobs/set_secrets.sh

if [ -z "$OPENAI_API_KEY" ]; then
  echo "Error: openAI key is empty!"
  exit 1
fi

source activate pcir
srun python -u pcir/methods/select_reformulate_Xshot.py --shot 1 --llm_model "meta-llama/Meta-Llama-3.1-8B-Instruct"