#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=reformulate
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=15
#SBATCH --time=01:00:00
#SBATCH --array=2-3
#SBATCH --output=outputs/slurm_output_sar_%A.out

# This script executes a STR pipeline.

module purge
module load 2024
module load Anaconda3/2024.06-1

source jobs/set_secrets.sh

if [ -z "$OPENAI_API_KEY" ]; then
  echo "Error: openAI key is empty!"
  exit 1
fi
SEED=$SLURM_ARRAY_TASK_ID

source activate ir2-2
srun python -u pcir/methods/reformulate.py --shot 3 --llm_model "meta-llama/Meta-Llama-3.1-8B-Instruct" --seed "$SEED"